In [29]:
#Listando o diretório onde estou
ls

 O volume na unidade C não tem nome.
 O Número de Série do Volume é 04F4-69E8

 Pasta de C:\Users\luis Shikasho\Documents\teste

20/12/2022  22:21    <DIR>          .
13/12/2022  22:15    <DIR>          ..
19/12/2022  23:19    <DIR>          .ipynb_checkpoints
19/12/2022  19:44            12.163 1-lojaA.xlsx
19/12/2022  19:46             9.819 2-lojaA.xlsx
19/12/2022  19:48             9.821 3-lojaA.xlsx
19/12/2022  19:52    <DIR>          OLD
19/12/2022  20:14             8.310 Untitled.ipynb
20/12/2022  22:21            41.575 Untitled1.ipynb
20/12/2022  22:02         7.076.406 vendas_linha_petshop.csv
               6 arquivo(s)      7.158.094 bytes
               4 pasta(s)   76.703.637.504 bytes disponíveis

In [30]:
#Importando o arquivo CSV para um dataframe
import pandas as pd

#fazendo a exibição de seu conteúdo
tabela = pd.read_csv("vendas_linha_petshop.csv", sep=";" , encoding="ISO-8859-1")
display(tabela)

,cod_pedido,regiao_pais,produto,valor,quantidade,valor_total_bruto,data,estado,formapagto,centro_distribuicao,responsavelpedido,valor_comissao,lucro_liquido,categoriaprod
0,1,Norte,Biscoito True Champion 300g,22,2.0,44,13/06/2019,Acre,Dinheiro,Rapid Pink,Carlos,"0,44","17,6",Alimentação
1,2,Norte,Biscoito True Champion 300g,21,2.0,42,03/01/2019,Amapá,Pix,Rapid Pink,Maria Linda,"0,42","16,8",Alimentação
2,3,Norte,Biscoito True Champion 300g,22,NaN,44,18/01/2019,Pará,Boleto Bancário,Rapid Pink,Julia,"0,88","35,2",Alimentação
3,4,Norte,Biscoito True Champion 300g,19,4.0,88,19/08/2019,Rondônia,Boleto Bancário,Rapid Pink,Yuri,"0,76","30,4",Alimentação
4,5,Norte,Biscoito True Champion 300g,22,2.0,44,18/10/2019,Tocantins,Cartão Crédito,Rapid Pink,Dolores,"0,44","17,6",Alimentação
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50278,50279,Sudeste,Bandana Disney Mickey Fábrica Petti,10,3.0,30,16/02/2019,Rio de Janeiro,Cartão Débito,Papa Léguas,Antonio,"0,48","16,8",Acessório
50279,50280,Sudeste,Bandana Disney Mickey Fábrica Petti,9,2.0,18,15/07/2019,Espírito Santo,Boleto Bancário,Papa Léguas,Tereza,"0,32","11,2",Acessório
50280,50281,Sul,Bandana Disney Mickey Fábrica Petti,11,3.0,33,06/05/2019,Paraná,Cartão Crédito,Tree True,Beatriz,"0,48","16,8",Acessório
50281,50282,Sul,Bandana Disney Mickey Fábrica Petti,12,1.0,12,27/05/2019,Santa Catarina,Cartão Débito,Tree True,Vitória,"0,26","9,1",Acessório
50282,50283,Sul,Bandana Disney Mickey Fábrica Petti,11,3.0,33,01/04/2019,Rio Grande do Sul,Pix,Tree True,Vivian,"0,66","23,1",Acessório

In [31]:
#Identificando as colunas aonde estão os dados missing e a quantidade de dados missing
print(tabela.isnull().sum())

cod_pedido               0
regiao_pais              0
produto                  0
valor                    0
quantidade             155
valor_total_bruto        0
data                     0
estado                   0
formapagto               0
centro_distribuicao      0
responsavelpedido        0
valor_comissao           0
lucro_liquido            0
categoriaprod            0
dtype: int64

In [32]:
#Exibindo apenas os dados missing
tabela[tabela.isnull().any(axis=1)]

,cod_pedido,regiao_pais,produto,valor,quantidade,valor_total_bruto,data,estado,formapagto,centro_distribuicao,responsavelpedido,valor_comissao,lucro_liquido,categoriaprod
2,3,Norte,Biscoito True Champion 300g,22,NaN,44,18/01/2019,Pará,Boleto Bancário,Rapid Pink,Julia,"0,88","35,2",Alimentação
157,158,Centro Oeste,Roupa para Cão Billaboard,34,NaN,68,08/09/2019,Goiás,Cartão Crédito,Grãos Blue,Maria Clara,"0,39","21,45",Acessório
281,282,Nordeste,Kit Banho e Tosa com Escova PetShop Cãopeon,63,NaN,126,21/11/2019,Maranhão,Pix,Gold Beach,Clarice,"1,28","51,2",Higiene e Limpeza
405,406,Nordeste,Ração Úmida Royal Canin Lata Veterinary Cães A...,28,NaN,56,17/08/2019,Ceará,Cartão Débito,Gold Beach,Neide,"1,44",36,Alimentação
529,530,Sudeste,Cama Coração Coroa Pet Nest Almofada Lavável,90,NaN,180,30/08/2019,Rio de Janeiro,Pix,Papa Léguas,Antonio,"1,68","50,4",Acessório
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49488,49489,Norte,"Ração Royal Canin Exigent Gatos Adultos 1,5Kg",93,NaN,186,04/04/2019,Roraima,Cartão Débito,Rapid Pink,Adriana,4,100,Alimentação
49489,49490,Norte,"Ração Royal Canin Exigent Gatos Adultos 1,5Kg",91,NaN,182,27/02/2019,Amazonas,Cartão Crédito,Rapid Pink,Silvia,"3,8",95,Alimentação
49490,49491,Centro Oeste,"Ração Royal Canin Exigent Gatos Adultos 1,5Kg",100,NaN,200,11/06/2019,Goiás,Dinheiro,Grãos Blue,Maria Clara,"3,6",90,Alimentação
49491,49492,Centro Oeste,"Ração Royal Canin Exigent Gatos Adultos 1,5Kg",98,NaN,196,08/11/2019,Mato Grosso,Boleto Bancário,Grãos Blue,Andressa,"3,76",94,Alimentação
49492,49493,Centro Oeste,"Ração Royal Canin Exigent Gatos Adultos 1,5Kg",93,NaN,186,17/07/2019,Mato Grosso do Sul,Pix,Grãos Blue,Ligia,"3,84",96,Alimentação

In [33]:
#Convertendo a tipagem dos tipos de dados de cada atributo
tabela.dtypes

cod_pedido               int64
regiao_pais             object
produto                 object
valor                    int64
quantidade             float64
valor_total_bruto        int64
data                    object
estado                  object
formapagto              object
centro_distribuicao     object
responsavelpedido       object
valor_comissao          object
lucro_liquido           object
categoriaprod           object
dtype: object

In [34]:
#Substituindo os valores missing por 0
tabela['quantidade'].fillna('0', inplace = True)

In [35]:
#Confirmando que não há mais dados missing
print(tabela.isnull().sum())

cod_pedido             0
regiao_pais            0
produto                0
valor                  0
quantidade             0
valor_total_bruto      0
data                   0
estado                 0
formapagto             0
centro_distribuicao    0
responsavelpedido      0
valor_comissao         0
lucro_liquido          0
categoriaprod          0
dtype: int64

In [36]:
#Visualizando a nova tabela sem os dados missing (substituido por 0)
display(tabela)

,cod_pedido,regiao_pais,produto,valor,quantidade,valor_total_bruto,data,estado,formapagto,centro_distribuicao,responsavelpedido,valor_comissao,lucro_liquido,categoriaprod
0,1,Norte,Biscoito True Champion 300g,22,2.0,44,13/06/2019,Acre,Dinheiro,Rapid Pink,Carlos,"0,44","17,6",Alimentação
1,2,Norte,Biscoito True Champion 300g,21,2.0,42,03/01/2019,Amapá,Pix,Rapid Pink,Maria Linda,"0,42","16,8",Alimentação
2,3,Norte,Biscoito True Champion 300g,22,0,44,18/01/2019,Pará,Boleto Bancário,Rapid Pink,Julia,"0,88","35,2",Alimentação
3,4,Norte,Biscoito True Champion 300g,19,4.0,88,19/08/2019,Rondônia,Boleto Bancário,Rapid Pink,Yuri,"0,76","30,4",Alimentação
4,5,Norte,Biscoito True Champion 300g,22,2.0,44,18/10/2019,Tocantins,Cartão Crédito,Rapid Pink,Dolores,"0,44","17,6",Alimentação
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50278,50279,Sudeste,Bandana Disney Mickey Fábrica Petti,10,3.0,30,16/02/2019,Rio de Janeiro,Cartão Débito,Papa Léguas,Antonio,"0,48","16,8",Acessório
50279,50280,Sudeste,Bandana Disney Mickey Fábrica Petti,9,2.0,18,15/07/2019,Espírito Santo,Boleto Bancário,Papa Léguas,Tereza,"0,32","11,2",Acessório
50280,50281,Sul,Bandana Disney Mickey Fábrica Petti,11,3.0,33,06/05/2019,Paraná,Cartão Crédito,Tree True,Beatriz,"0,48","16,8",Acessório
50281,50282,Sul,Bandana Disney Mickey Fábrica Petti,12,1.0,12,27/05/2019,Santa Catarina,Cartão Débito,Tree True,Vitória,"0,26","9,1",Acessório
50282,50283,Sul,Bandana Disney Mickey Fábrica Petti,11,3.0,33,01/04/2019,Rio Grande do Sul,Pix,Tree True,Vivian,"0,66","23,1",Acessório

In [39]:
#Exportando o dataframe sem missing para um CSV
tabela.to_csv('nomissing_vendas_linha_petshop.csv')